version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: clase13
       MYSQL_USER: devuser
       MYSQL_PASSWORD: devpass
     ports:
       - "9906:3306"

volumes:
    db_data:
      
# sudo mkdir /var/lib/mysql
# docker system prune -a
# docker volume prune

