# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db_C8
    environment:
      MYSQL_ROOT_PASSWORD: rootsecretpass
      MYSQL_DATABASE: clase8
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build:
      context: ./docker/php
    container_name: php_web_C8
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    tty: true
    